import { ArrowLeft } from 'lucide-react'
import { useNavigate } from 'react-router-dom'

export default function Terms() {
  const nav = useNavigate()
  return (
    <div className="page">
      <div className="page-header">
        <div style={{display:'flex', alignItems:'center', gap:8}}>
          <button style={{background:'none', border:'none', cursor:'pointer', padding:4, color:'var(--text)'}} onClick={() => nav(-1)}><ArrowLeft size={20}/></button>
          <h2 style={{fontSize:20, fontWeight:800}}>Terms of Service</h2>
        </div>
      </div>

      <div style={{background:'var(--surface)', border:'1px solid var(--border2)', borderRadius:16, padding:20}}>
        <div style={{fontSize:11, color:'var(--text3)', marginBottom:16}}>Last updated: April 2026</div>

        {[
          { title: '1. Acceptance of Terms', body: 'By accessing or using Viya ("the App"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the App.' },
          { title: '2. Description of Service', body: 'Viya is an AI-powered personal finance and habit tracking assistant. The App provides expense tracking, goal setting, habit monitoring, AI chat assistance, and WhatsApp integration. Viya is not a licensed financial advisor — all suggestions are informational only.' },
          { title: '3. User Accounts', body: 'You must provide a valid phone number to create an account. You are responsible for maintaining the confidentiality of your account credentials. You must be at least 18 years old to use premium features.' },
          { title: '4. User Data & Privacy', body: 'We collect only data necessary for the App to function: phone number, financial transactions you log, goals, habits, and chat history. Your data is encrypted at rest using AES-256 encryption. We never sell your personal data to third parties. You can request complete data deletion at any time.' },
          { title: '5. Financial Information Disclaimer', body: 'Viya provides general financial information, NOT professional financial advice. Investment suggestions are educational and not recommendations. Always consult a certified financial advisor (CA/CFP) for major financial decisions. We are not liable for any financial losses.' },
          { title: '6. AI Chat & WhatsApp', body: 'AI responses are generated by machine learning models and may occasionally be inaccurate. WhatsApp integration is subject to Meta\'s Terms of Service. We do not store WhatsApp messages beyond what is necessary for the service.' },
          { title: '7. Premium Subscription', body: 'Premium features are available at ₹149/month. Subscriptions auto-renew unless cancelled. Cancellation takes effect at the end of the billing period. Refunds are available within 7 days of purchase.' },
          { title: '8. Prohibited Use', body: 'You may not: use the App for illegal activities, attempt to reverse-engineer the App, share your account with others, use automated tools to access the service, or upload harmful content.' },
          { title: '9. Intellectual Property', body: 'All content, design, and code of Viya are owned by the developer. "Viya" and the Viya logo are trademarks. You may not reproduce or redistribute any part of the App.' },
          { title: '10. Limitation of Liability', body: 'Viya is provided "as is" without warranties. We are not liable for: data loss due to device issues, inaccurate AI responses, third-party service outages, or financial decisions made based on App suggestions.' },
          { title: '11. Changes to Terms', body: 'We may update these terms at any time. Continued use of the App after changes constitutes acceptance. We will notify users of material changes via in-app notification or WhatsApp.' },
          { title: '12. Contact', body: 'For questions about these terms, contact us at support@heyviya.com or through the in-app Help & Support page.' },
        ].map((s, i) => (
          <div key={i} style={{marginBottom:16}}>
            <div style={{fontSize:14, fontWeight:700, marginBottom:4, color:'var(--text)'}}>{s.title}</div>
            <div style={{fontSize:13, color:'var(--text2)', lineHeight:1.6}}>{s.body}</div>
          </div>
        ))}

        <div style={{borderTop:'1px solid var(--border)', paddingTop:16, marginTop:8, textAlign:'center', fontSize:12, color:'var(--text3)'}}>
          © 2026 Viya. All rights reserved.
        </div>
      </div>
    </div>
  )
}
